# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /private/var/folders/zz/zyxvpxvq6csfxvn_n00012xm0008qd/T/AppTranslocation/7C8941B1-67D8-4D16-907C-A8EDB4E5E948/d/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /private/var/folders/zz/zyxvpxvq6csfxvn_n00012xm0008qd/T/AppTranslocation/7C8941B1-67D8-4D16-907C-A8EDB4E5E948/d/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/blomo/corawara

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/blomo/corawara

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/private/var/folders/zz/zyxvpxvq6csfxvn_n00012xm0008qd/T/AppTranslocation/7C8941B1-67D8-4D16-907C-A8EDB4E5E948/d/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/private/var/folders/zz/zyxvpxvq6csfxvn_n00012xm0008qd/T/AppTranslocation/7C8941B1-67D8-4D16-907C-A8EDB4E5E948/d/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blomo/corawara/CMakeFiles /Users/blomo/corawara/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blomo/corawara/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asm

# Build rule for target.
asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asm
.PHONY : asm

# fast build rule for target.
asm/fast:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/build
.PHONY : asm/fast

#=============================================================================
# Target rules for targets named corewar

# Build rule for target.
corewar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 corewar
.PHONY : corewar

# fast build rule for target.
corewar/fast:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/build
.PHONY : corewar/fast

src/asm/assembler.o: src/asm/assembler.c.o

.PHONY : src/asm/assembler.o

# target to build an object file
src/asm/assembler.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/assembler.c.o
.PHONY : src/asm/assembler.c.o

src/asm/assembler.i: src/asm/assembler.c.i

.PHONY : src/asm/assembler.i

# target to preprocess a source file
src/asm/assembler.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/assembler.c.i
.PHONY : src/asm/assembler.c.i

src/asm/assembler.s: src/asm/assembler.c.s

.PHONY : src/asm/assembler.s

# target to generate assembly for a file
src/asm/assembler.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/assembler.c.s
.PHONY : src/asm/assembler.c.s

src/asm/champ_generator.o: src/asm/champ_generator.c.o

.PHONY : src/asm/champ_generator.o

# target to build an object file
src/asm/champ_generator.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/champ_generator.c.o
.PHONY : src/asm/champ_generator.c.o

src/asm/champ_generator.i: src/asm/champ_generator.c.i

.PHONY : src/asm/champ_generator.i

# target to preprocess a source file
src/asm/champ_generator.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/champ_generator.c.i
.PHONY : src/asm/champ_generator.c.i

src/asm/champ_generator.s: src/asm/champ_generator.c.s

.PHONY : src/asm/champ_generator.s

# target to generate assembly for a file
src/asm/champ_generator.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/champ_generator.c.s
.PHONY : src/asm/champ_generator.c.s

src/asm/disassembler.o: src/asm/disassembler.c.o

.PHONY : src/asm/disassembler.o

# target to build an object file
src/asm/disassembler.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/disassembler.c.o
.PHONY : src/asm/disassembler.c.o

src/asm/disassembler.i: src/asm/disassembler.c.i

.PHONY : src/asm/disassembler.i

# target to preprocess a source file
src/asm/disassembler.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/disassembler.c.i
.PHONY : src/asm/disassembler.c.i

src/asm/disassembler.s: src/asm/disassembler.c.s

.PHONY : src/asm/disassembler.s

# target to generate assembly for a file
src/asm/disassembler.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/disassembler.c.s
.PHONY : src/asm/disassembler.c.s

src/asm/lexer.o: src/asm/lexer.c.o

.PHONY : src/asm/lexer.o

# target to build an object file
src/asm/lexer.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/lexer.c.o
.PHONY : src/asm/lexer.c.o

src/asm/lexer.i: src/asm/lexer.c.i

.PHONY : src/asm/lexer.i

# target to preprocess a source file
src/asm/lexer.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/lexer.c.i
.PHONY : src/asm/lexer.c.i

src/asm/lexer.s: src/asm/lexer.c.s

.PHONY : src/asm/lexer.s

# target to generate assembly for a file
src/asm/lexer.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/lexer.c.s
.PHONY : src/asm/lexer.c.s

src/asm/main.o: src/asm/main.c.o

.PHONY : src/asm/main.o

# target to build an object file
src/asm/main.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/main.c.o
.PHONY : src/asm/main.c.o

src/asm/main.i: src/asm/main.c.i

.PHONY : src/asm/main.i

# target to preprocess a source file
src/asm/main.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/main.c.i
.PHONY : src/asm/main.c.i

src/asm/main.s: src/asm/main.c.s

.PHONY : src/asm/main.s

# target to generate assembly for a file
src/asm/main.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/main.c.s
.PHONY : src/asm/main.c.s

src/asm/read_args.o: src/asm/read_args.c.o

.PHONY : src/asm/read_args.o

# target to build an object file
src/asm/read_args.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/read_args.c.o
.PHONY : src/asm/read_args.c.o

src/asm/read_args.i: src/asm/read_args.c.i

.PHONY : src/asm/read_args.i

# target to preprocess a source file
src/asm/read_args.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/read_args.c.i
.PHONY : src/asm/read_args.c.i

src/asm/read_args.s: src/asm/read_args.c.s

.PHONY : src/asm/read_args.s

# target to generate assembly for a file
src/asm/read_args.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/read_args.c.s
.PHONY : src/asm/read_args.c.s

src/asm/writer.o: src/asm/writer.c.o

.PHONY : src/asm/writer.o

# target to build an object file
src/asm/writer.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/writer.c.o
.PHONY : src/asm/writer.c.o

src/asm/writer.i: src/asm/writer.c.i

.PHONY : src/asm/writer.i

# target to preprocess a source file
src/asm/writer.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/writer.c.i
.PHONY : src/asm/writer.c.i

src/asm/writer.s: src/asm/writer.c.s

.PHONY : src/asm/writer.s

# target to generate assembly for a file
src/asm/writer.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/src/asm/writer.c.s
.PHONY : src/asm/writer.c.s

src/vm/checkop1.o: src/vm/checkop1.c.o

.PHONY : src/vm/checkop1.o

# target to build an object file
src/vm/checkop1.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop1.c.o
.PHONY : src/vm/checkop1.c.o

src/vm/checkop1.i: src/vm/checkop1.c.i

.PHONY : src/vm/checkop1.i

# target to preprocess a source file
src/vm/checkop1.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop1.c.i
.PHONY : src/vm/checkop1.c.i

src/vm/checkop1.s: src/vm/checkop1.c.s

.PHONY : src/vm/checkop1.s

# target to generate assembly for a file
src/vm/checkop1.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop1.c.s
.PHONY : src/vm/checkop1.c.s

src/vm/checkop2.o: src/vm/checkop2.c.o

.PHONY : src/vm/checkop2.o

# target to build an object file
src/vm/checkop2.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop2.c.o
.PHONY : src/vm/checkop2.c.o

src/vm/checkop2.i: src/vm/checkop2.c.i

.PHONY : src/vm/checkop2.i

# target to preprocess a source file
src/vm/checkop2.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop2.c.i
.PHONY : src/vm/checkop2.c.i

src/vm/checkop2.s: src/vm/checkop2.c.s

.PHONY : src/vm/checkop2.s

# target to generate assembly for a file
src/vm/checkop2.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/checkop2.c.s
.PHONY : src/vm/checkop2.c.s

src/vm/game_main_loop.o: src/vm/game_main_loop.c.o

.PHONY : src/vm/game_main_loop.o

# target to build an object file
src/vm/game_main_loop.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/game_main_loop.c.o
.PHONY : src/vm/game_main_loop.c.o

src/vm/game_main_loop.i: src/vm/game_main_loop.c.i

.PHONY : src/vm/game_main_loop.i

# target to preprocess a source file
src/vm/game_main_loop.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/game_main_loop.c.i
.PHONY : src/vm/game_main_loop.c.i

src/vm/game_main_loop.s: src/vm/game_main_loop.c.s

.PHONY : src/vm/game_main_loop.s

# target to generate assembly for a file
src/vm/game_main_loop.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/game_main_loop.c.s
.PHONY : src/vm/game_main_loop.c.s

src/vm/init_arena.o: src/vm/init_arena.c.o

.PHONY : src/vm/init_arena.o

# target to build an object file
src/vm/init_arena.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/init_arena.c.o
.PHONY : src/vm/init_arena.c.o

src/vm/init_arena.i: src/vm/init_arena.c.i

.PHONY : src/vm/init_arena.i

# target to preprocess a source file
src/vm/init_arena.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/init_arena.c.i
.PHONY : src/vm/init_arena.c.i

src/vm/init_arena.s: src/vm/init_arena.c.s

.PHONY : src/vm/init_arena.s

# target to generate assembly for a file
src/vm/init_arena.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/init_arena.c.s
.PHONY : src/vm/init_arena.c.s

src/vm/main.o: src/vm/main.c.o

.PHONY : src/vm/main.o

# target to build an object file
src/vm/main.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/main.c.o
.PHONY : src/vm/main.c.o

src/vm/main.i: src/vm/main.c.i

.PHONY : src/vm/main.i

# target to preprocess a source file
src/vm/main.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/main.c.i
.PHONY : src/vm/main.c.i

src/vm/main.s: src/vm/main.c.s

.PHONY : src/vm/main.s

# target to generate assembly for a file
src/vm/main.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/main.c.s
.PHONY : src/vm/main.c.s

src/vm/make_one_turn.o: src/vm/make_one_turn.c.o

.PHONY : src/vm/make_one_turn.o

# target to build an object file
src/vm/make_one_turn.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/make_one_turn.c.o
.PHONY : src/vm/make_one_turn.c.o

src/vm/make_one_turn.i: src/vm/make_one_turn.c.i

.PHONY : src/vm/make_one_turn.i

# target to preprocess a source file
src/vm/make_one_turn.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/make_one_turn.c.i
.PHONY : src/vm/make_one_turn.c.i

src/vm/make_one_turn.s: src/vm/make_one_turn.c.s

.PHONY : src/vm/make_one_turn.s

# target to generate assembly for a file
src/vm/make_one_turn.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/make_one_turn.c.s
.PHONY : src/vm/make_one_turn.c.s

src/vm/operation.o: src/vm/operation.c.o

.PHONY : src/vm/operation.o

# target to build an object file
src/vm/operation.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/operation.c.o
.PHONY : src/vm/operation.c.o

src/vm/operation.i: src/vm/operation.c.i

.PHONY : src/vm/operation.i

# target to preprocess a source file
src/vm/operation.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/operation.c.i
.PHONY : src/vm/operation.c.i

src/vm/operation.s: src/vm/operation.c.s

.PHONY : src/vm/operation.s

# target to generate assembly for a file
src/vm/operation.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/operation.c.s
.PHONY : src/vm/operation.c.s

src/vm/parse_file.o: src/vm/parse_file.c.o

.PHONY : src/vm/parse_file.o

# target to build an object file
src/vm/parse_file.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/parse_file.c.o
.PHONY : src/vm/parse_file.c.o

src/vm/parse_file.i: src/vm/parse_file.c.i

.PHONY : src/vm/parse_file.i

# target to preprocess a source file
src/vm/parse_file.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/parse_file.c.i
.PHONY : src/vm/parse_file.c.i

src/vm/parse_file.s: src/vm/parse_file.c.s

.PHONY : src/vm/parse_file.s

# target to generate assembly for a file
src/vm/parse_file.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/parse_file.c.s
.PHONY : src/vm/parse_file.c.s

src/vm/safe_exit.o: src/vm/safe_exit.c.o

.PHONY : src/vm/safe_exit.o

# target to build an object file
src/vm/safe_exit.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/safe_exit.c.o
.PHONY : src/vm/safe_exit.c.o

src/vm/safe_exit.i: src/vm/safe_exit.c.i

.PHONY : src/vm/safe_exit.i

# target to preprocess a source file
src/vm/safe_exit.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/safe_exit.c.i
.PHONY : src/vm/safe_exit.c.i

src/vm/safe_exit.s: src/vm/safe_exit.c.s

.PHONY : src/vm/safe_exit.s

# target to generate assembly for a file
src/vm/safe_exit.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/safe_exit.c.s
.PHONY : src/vm/safe_exit.c.s

src/vm/timeline_mngmnt.o: src/vm/timeline_mngmnt.c.o

.PHONY : src/vm/timeline_mngmnt.o

# target to build an object file
src/vm/timeline_mngmnt.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/timeline_mngmnt.c.o
.PHONY : src/vm/timeline_mngmnt.c.o

src/vm/timeline_mngmnt.i: src/vm/timeline_mngmnt.c.i

.PHONY : src/vm/timeline_mngmnt.i

# target to preprocess a source file
src/vm/timeline_mngmnt.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/timeline_mngmnt.c.i
.PHONY : src/vm/timeline_mngmnt.c.i

src/vm/timeline_mngmnt.s: src/vm/timeline_mngmnt.c.s

.PHONY : src/vm/timeline_mngmnt.s

# target to generate assembly for a file
src/vm/timeline_mngmnt.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/timeline_mngmnt.c.s
.PHONY : src/vm/timeline_mngmnt.c.s

src/vm/validate_input.o: src/vm/validate_input.c.o

.PHONY : src/vm/validate_input.o

# target to build an object file
src/vm/validate_input.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/validate_input.c.o
.PHONY : src/vm/validate_input.c.o

src/vm/validate_input.i: src/vm/validate_input.c.i

.PHONY : src/vm/validate_input.i

# target to preprocess a source file
src/vm/validate_input.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/validate_input.c.i
.PHONY : src/vm/validate_input.c.i

src/vm/validate_input.s: src/vm/validate_input.c.s

.PHONY : src/vm/validate_input.s

# target to generate assembly for a file
src/vm/validate_input.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/src/vm/validate_input.c.s
.PHONY : src/vm/validate_input.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... asm"
	@echo "... corewar"
	@echo "... src/asm/assembler.o"
	@echo "... src/asm/assembler.i"
	@echo "... src/asm/assembler.s"
	@echo "... src/asm/champ_generator.o"
	@echo "... src/asm/champ_generator.i"
	@echo "... src/asm/champ_generator.s"
	@echo "... src/asm/disassembler.o"
	@echo "... src/asm/disassembler.i"
	@echo "... src/asm/disassembler.s"
	@echo "... src/asm/lexer.o"
	@echo "... src/asm/lexer.i"
	@echo "... src/asm/lexer.s"
	@echo "... src/asm/main.o"
	@echo "... src/asm/main.i"
	@echo "... src/asm/main.s"
	@echo "... src/asm/read_args.o"
	@echo "... src/asm/read_args.i"
	@echo "... src/asm/read_args.s"
	@echo "... src/asm/writer.o"
	@echo "... src/asm/writer.i"
	@echo "... src/asm/writer.s"
	@echo "... src/vm/checkop1.o"
	@echo "... src/vm/checkop1.i"
	@echo "... src/vm/checkop1.s"
	@echo "... src/vm/checkop2.o"
	@echo "... src/vm/checkop2.i"
	@echo "... src/vm/checkop2.s"
	@echo "... src/vm/game_main_loop.o"
	@echo "... src/vm/game_main_loop.i"
	@echo "... src/vm/game_main_loop.s"
	@echo "... src/vm/init_arena.o"
	@echo "... src/vm/init_arena.i"
	@echo "... src/vm/init_arena.s"
	@echo "... src/vm/main.o"
	@echo "... src/vm/main.i"
	@echo "... src/vm/main.s"
	@echo "... src/vm/make_one_turn.o"
	@echo "... src/vm/make_one_turn.i"
	@echo "... src/vm/make_one_turn.s"
	@echo "... src/vm/operation.o"
	@echo "... src/vm/operation.i"
	@echo "... src/vm/operation.s"
	@echo "... src/vm/parse_file.o"
	@echo "... src/vm/parse_file.i"
	@echo "... src/vm/parse_file.s"
	@echo "... src/vm/safe_exit.o"
	@echo "... src/vm/safe_exit.i"
	@echo "... src/vm/safe_exit.s"
	@echo "... src/vm/timeline_mngmnt.o"
	@echo "... src/vm/timeline_mngmnt.i"
	@echo "... src/vm/timeline_mngmnt.s"
	@echo "... src/vm/validate_input.o"
	@echo "... src/vm/validate_input.i"
	@echo "... src/vm/validate_input.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

