# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ehugh-be <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 15:05:00 by ehugh-be          #+#    #+#              #
#    Updated: 2019/10/11 14:15:53 by ehugh-be         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = lib2list.a
DEPS_PATH = ../libstd/
DEPS_SRC = ft_memalloc.c ft_memcpy.c
DEPS = $(addprefix $(DEPS_PATH), $(DEPS_SRC))
include ../Rules