# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ehugh-be <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 15:05:00 by ehugh-be          #+#    #+#              #
#    Updated: 2019/04/01 21:06:56 by ehugh-be         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libvec.a
DEPS_PATH = ../libstd/
DEPS_SRC = ft_memcpy.c ft_realloc.c ft_putstr_fd.c ft_bzero.c ft_memmove.c
DEPS = $(addprefix $(DEPS_PATH), $(DEPS_SRC))
include ../Rules

